-- Formalizar columnas acd3..ex4 en SQL (ya existen en TS types y en producción pero sin migración)
ALTER TABLE calificaciones
  ADD COLUMN IF NOT EXISTS acd3 NUMERIC(5,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ta3  NUMERIC(5,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS pe3  NUMERIC(5,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ex3  NUMERIC(5,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS acd4 NUMERIC(5,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ta4  NUMERIC(5,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS pe4  NUMERIC(5,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ex4  NUMERIC(5,2) DEFAULT NULL;
